/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poofinal;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import poofinal.Aluno;
import poofinal.MatriculaErroException;

/**
 *
 * @author johnn
 */
public class NovaInterfaceGrafica extends javax.swing.JFrame {
     
    List<Aluno> alunos;
    /**
     * Creates new form NovaInterfaceGrafica
     */
    public NovaInterfaceGrafica() {
        initComponents();
        alunos = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Principal = new javax.swing.JPanel();
        Opções_do_painel = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Aluno = new javax.swing.JButton();
        _TXT = new javax.swing.JButton();
        DE_TXT = new javax.swing.JButton();
        HIBERNATE = new javax.swing.JButton();
        Opção_Aluno = new javax.swing.JPanel();
        Voltar_para_OP = new javax.swing.JButton();
        MATRICULA = new javax.swing.JLabel();
        CPF = new javax.swing.JLabel();
        NOME = new javax.swing.JLabel();
        DATA_DE_NASCIMENTO = new javax.swing.JLabel();
        TELEFONE = new javax.swing.JLabel();
        IDADE = new javax.swing.JLabel();
        FIELD_MATRICULA = new javax.swing.JTextField();
        FIELD_NOME = new javax.swing.JTextField();
        FIELD_DATA_DE_NASCIMENTO = new javax.swing.JTextField();
        FIELD_CPF = new javax.swing.JTextField();
        FIELD_TELEFONE = new javax.swing.JTextField();
        FIELD_IDADE = new javax.swing.JTextField();
        ADICIONAR = new javax.swing.JButton();
        ADCIONAR_3º = new javax.swing.JButton();
        LABEL_BUSCAR_ALUNO = new javax.swing.JLabel();
        FIELD_BUSCAR_ALUNO = new javax.swing.JTextField();
        BUSCAR_ALUNO = new javax.swing.JButton();
        TOTAL_DE_ALUNOS = new javax.swing.JButton();
        LABEL_REMOVER_ALUNO = new javax.swing.JLabel();
        FIELD_REMOVER_ALUNO = new javax.swing.JTextField();
        REMOVER_ALUNO = new javax.swing.JButton();
        MAIS_NOVO_VELHO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Painel_Principal.setLayout(new java.awt.CardLayout());

        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Sistema de Gerenciamento de Aluno");
        Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Aluno.setText("Aluno");
        Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlunoActionPerformed(evt);
            }
        });

        _TXT.setText(".TXT");

        DE_TXT.setText("De .TXT");

        HIBERNATE.setText("Hibernate");

        javax.swing.GroupLayout Opções_do_painelLayout = new javax.swing.GroupLayout(Opções_do_painel);
        Opções_do_painel.setLayout(Opções_do_painelLayout);
        Opções_do_painelLayout.setHorizontalGroup(
            Opções_do_painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Opções_do_painelLayout.createSequentialGroup()
                .addGroup(Opções_do_painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Opções_do_painelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(Aluno)
                        .addGap(18, 18, 18)
                        .addComponent(_TXT)
                        .addGap(18, 18, 18)
                        .addComponent(DE_TXT)
                        .addGap(18, 18, 18)
                        .addComponent(HIBERNATE))
                    .addGroup(Opções_do_painelLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        Opções_do_painelLayout.setVerticalGroup(
            Opções_do_painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Opções_do_painelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addGroup(Opções_do_painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aluno)
                    .addComponent(_TXT)
                    .addComponent(DE_TXT)
                    .addComponent(HIBERNATE))
                .addGap(34, 34, 34))
        );

        Painel_Principal.add(Opções_do_painel, "Opção_do_Painel");

        Voltar_para_OP.setText("Voltar");
        Voltar_para_OP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voltar_para_OPActionPerformed(evt);
            }
        });

        MATRICULA.setText("MATRICULA:");

        CPF.setText("CPF:");

        NOME.setText("NOME:");

        DATA_DE_NASCIMENTO.setText("DATA DE NASCIMENTO:");

        TELEFONE.setText("TELEFONE:");

        IDADE.setText("IDADE:");

        ADICIONAR.setText("ADICIONAR");
        ADICIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADICIONARActionPerformed(evt);
            }
        });

        ADCIONAR_3º.setText("ADICIONAR 3º");

        LABEL_BUSCAR_ALUNO.setText("BUSCAR ALUNO:");

        FIELD_BUSCAR_ALUNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIELD_BUSCAR_ALUNOActionPerformed(evt);
            }
        });

        BUSCAR_ALUNO.setText("BUSCAR");

        TOTAL_DE_ALUNOS.setText("TOTAL DE ALUNOS");
        TOTAL_DE_ALUNOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTAL_DE_ALUNOSActionPerformed(evt);
            }
        });

        LABEL_REMOVER_ALUNO.setText("REMOVER ALUNO:");

        FIELD_REMOVER_ALUNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIELD_REMOVER_ALUNOActionPerformed(evt);
            }
        });

        REMOVER_ALUNO.setText("REMOVER");

        MAIS_NOVO_VELHO.setText("MAIS NOVO/MAIS VELHO");
        MAIS_NOVO_VELHO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAIS_NOVO_VELHOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Opção_AlunoLayout = new javax.swing.GroupLayout(Opção_Aluno);
        Opção_Aluno.setLayout(Opção_AlunoLayout);
        Opção_AlunoLayout.setHorizontalGroup(
            Opção_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Opção_AlunoLayout.createSequentialGroup()
                .addGroup(Opção_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Opção_AlunoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Voltar_para_OP))
                    .addGroup(Opção_AlunoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(Opção_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Opção_AlunoLayout.createSequentialGroup()
                                .addComponent(ADICIONAR)
                                .addGap(18, 18, 18)
                                .addComponent(ADCIONAR_3º)
                                .addGap(18, 18, 18)
                                .addComponent(TOTAL_DE_ALUNOS)
                                .addGap(18, 18, 18)
                                .addComponent(MAIS_NOVO_VELHO))
                            .addGroup(Opção_AlunoLayout.createSequentialGroup()
                                .addGroup(Opção_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Opção_AlunoLayout.createSequentialGroup()
                                        .addComponent(DATA_DE_NASCIMENTO)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FIELD_DATA_DE_NASCIMENTO))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Opção_AlunoLayout.createSequentialGroup()
                                        .addComponent(NOME)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FIELD_NOME))
                                    .addGroup(Opção_AlunoLayout.createSequentialGroup()
                                        .addComponent(MATRICULA)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FIELD_MATRICULA, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Opção_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(Opção_AlunoLayout.createSequentialGroup()
                                        .addComponent(CPF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FIELD_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Opção_AlunoLayout.createSequentialGroup()
                                        .addComponent(TELEFONE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FIELD_TELEFONE))
                                    .addGroup(Opção_AlunoLayout.createSequentialGroup()
                                        .addComponent(IDADE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FIELD_IDADE))))
                            .addGroup(Opção_AlunoLayout.createSequentialGroup()
                                .addGroup(Opção_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Opção_AlunoLayout.createSequentialGroup()
                                        .addComponent(LABEL_REMOVER_ALUNO)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FIELD_REMOVER_ALUNO))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Opção_AlunoLayout.createSequentialGroup()
                                        .addComponent(LABEL_BUSCAR_ALUNO)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FIELD_BUSCAR_ALUNO, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Opção_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(REMOVER_ALUNO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BUSCAR_ALUNO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        Opção_AlunoLayout.setVerticalGroup(
            Opção_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Opção_AlunoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Opção_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MATRICULA)
                    .addComponent(FIELD_MATRICULA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPF)
                    .addComponent(FIELD_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Opção_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOME)
                    .addComponent(FIELD_NOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TELEFONE)
                    .addComponent(FIELD_TELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Opção_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DATA_DE_NASCIMENTO)
                    .addComponent(FIELD_DATA_DE_NASCIMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDADE)
                    .addComponent(FIELD_IDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Opção_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MAIS_NOVO_VELHO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TOTAL_DE_ALUNOS)
                    .addComponent(ADCIONAR_3º)
                    .addComponent(ADICIONAR))
                .addGap(55, 55, 55)
                .addGroup(Opção_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABEL_BUSCAR_ALUNO)
                    .addComponent(FIELD_BUSCAR_ALUNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUSCAR_ALUNO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Opção_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABEL_REMOVER_ALUNO)
                    .addComponent(FIELD_REMOVER_ALUNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REMOVER_ALUNO))
                .addGap(87, 87, 87)
                .addComponent(Voltar_para_OP)
                .addGap(25, 25, 25))
        );

        Painel_Principal.add(Opção_Aluno, "Opção_Aluno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlunoActionPerformed
       CardLayout  c1 = (CardLayout) Painel_Principal.getLayout();
       c1.show(Painel_Principal,"Opção_Aluno");// TODO add your handling code here:
    }//GEN-LAST:event_AlunoActionPerformed

    private void Voltar_para_OPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Voltar_para_OPActionPerformed
        CardLayout c1 = (CardLayout) Painel_Principal.getLayout();
        c1.show(Painel_Principal,"Opção_do_Painel");
    }//GEN-LAST:event_Voltar_para_OPActionPerformed

    private void FIELD_BUSCAR_ALUNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIELD_BUSCAR_ALUNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIELD_BUSCAR_ALUNOActionPerformed

    private void TOTAL_DE_ALUNOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTAL_DE_ALUNOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TOTAL_DE_ALUNOSActionPerformed

    private void FIELD_REMOVER_ALUNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIELD_REMOVER_ALUNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIELD_REMOVER_ALUNOActionPerformed

    private void MAIS_NOVO_VELHOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAIS_NOVO_VELHOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MAIS_NOVO_VELHOActionPerformed

    private void ADICIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADICIONARActionPerformed
     try {
         String matricula = FIELD_MATRICULA.getText().trim();
        String nome = FIELD_NOME.getText();
        String dataNascimento = FIELD_DATA_DE_NASCIMENTO.getText().trim();
        String telefone = FIELD_TELEFONE.getText().trim();
        String cpf = FIELD_CPF.getText().trim();
        String idadeStr = FIELD_IDADE.getText().trim();
        if(matricula.isEmpty()) {
            throw new MatriculaErroException("Erro: a matricula está vazia.");
        }
        for(Aluno existem: alunos) {
            if(existem.getMatricula().equalsIgnoreCase(matricula)) {
                throw new MatriculaErroException("Matricula já cadastrada.");
            }
}
        if(nome.isEmpty()) {   
            JOptionPane.showMessageDialog(this,"Nome obrigatório."," ",JOptionPane.ERROR_MESSAGE);           
return;
}
if (idadeStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo IDADE é obrigatório.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            FIELD_IDADE.requestFocus();
            return;
        }
int idade = Integer.parseInt(idadeStr);
Aluno novoAluno = new Aluno(nome, matricula, dataNascimento, telefone, cpf, idade);
alunos.add(novoAluno);
        FIELD_MATRICULA.setText("");
        FIELD_NOME.setText("");
        FIELD_DATA_DE_NASCIMENTO.setText("");
        FIELD_TELEFONE.setText("");
        FIELD_CPF.setText("");
        FIELD_IDADE.setText("");

        FIELD_MATRICULA.requestFocus();
        } catch(MatriculaErroException e) {
         JOptionPane.showMessageDialog(this, e.getMessage(), "Erro na Matrícula", JOptionPane.ERROR_MESSAGE);
        FIELD_MATRICULA.requestFocus();
        FIELD_MATRICULA.selectAll();
     }
        
        
     } 
        // TODO add your handling code here:
    }//GEN-LAST:event_ADICIONARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaInterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaInterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaInterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaInterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaInterfaceGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADCIONAR_3º;
    private javax.swing.JButton ADICIONAR;
    private javax.swing.JButton Aluno;
    private javax.swing.JButton BUSCAR_ALUNO;
    private javax.swing.JLabel CPF;
    private javax.swing.JLabel DATA_DE_NASCIMENTO;
    private javax.swing.JButton DE_TXT;
    private javax.swing.JTextField FIELD_BUSCAR_ALUNO;
    private javax.swing.JTextField FIELD_CPF;
    private javax.swing.JTextField FIELD_DATA_DE_NASCIMENTO;
    private javax.swing.JTextField FIELD_IDADE;
    private javax.swing.JTextField FIELD_MATRICULA;
    private javax.swing.JTextField FIELD_NOME;
    private javax.swing.JTextField FIELD_REMOVER_ALUNO;
    private javax.swing.JTextField FIELD_TELEFONE;
    private javax.swing.JButton HIBERNATE;
    private javax.swing.JLabel IDADE;
    private javax.swing.JLabel LABEL_BUSCAR_ALUNO;
    private javax.swing.JLabel LABEL_REMOVER_ALUNO;
    private javax.swing.JButton MAIS_NOVO_VELHO;
    private javax.swing.JLabel MATRICULA;
    private javax.swing.JLabel NOME;
    private javax.swing.JPanel Opção_Aluno;
    private javax.swing.JPanel Opções_do_painel;
    private javax.swing.JPanel Painel_Principal;
    private javax.swing.JButton REMOVER_ALUNO;
    private javax.swing.JLabel TELEFONE;
    private javax.swing.JButton TOTAL_DE_ALUNOS;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton Voltar_para_OP;
    private javax.swing.JButton _TXT;
    // End of variables declaration//GEN-END:variables
}
